import styles from '../styles/Home.module.css'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import { Header } from 'components/Header'
import { Landing } from 'components/Landing'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <Landing />
      </main>

    </div>
  )
}

export default Home
